package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/graph/model"
)

// PermissionExplanation is the resolver for the permissionExplanation field.
func (r *queryResolver) PermissionExplanation(ctx context.Context, userID string, spaceID *string, roomID *string) ([]*model.PermissionExplanation, error) {
	viewer, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if roomID != nil && *roomID != "" && (spaceID == nil || *spaceID == "") {
		return nil, fmt.Errorf("roomId requires spaceId")
	}

	scopedSpaceID := ""
	if spaceID != nil {
		scopedSpaceID = *spaceID
	}
	scopedRoomID := ""
	if roomID != nil {
		scopedRoomID = *roomID
	}

	if err := r.authorizePermissionExplanation(ctx, viewer.Id, userID, scopedSpaceID, scopedRoomID); err != nil {
		return nil, err
	}

	results, err := r.core.PermResolver().ExplainAllPermissions(ctx, userID, scopedSpaceID, scopedRoomID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.PermissionExplanation, 0, len(results))
	for _, exp := range results {
		out = append(out, toModelExplanation(exp))
	}
	return out, nil
}
