package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// MyEvents is the resolver for the myServerEvents field.
//
// Backed by a single core stream (StreamMyEvents) that consumes the
// unified `live.server.>` subject root — room events from the
// SERVER_EVENTS republish, transient room/user/space/config events from
// direct NATS Core publishes, plus presence and heartbeats.
func (r *subscriptionResolver) MyEvents(ctx context.Context) (<-chan *corev1.Event, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	events, err := r.core.StreamMyEvents(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("subscribe events: %w", err)
	}
	return events, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
